# Generated by Django 6.0.5 on 2026-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Andamento'), ('C', 'Concluída')], max_length=1)),
                ('prazo', models.DateField()),
            ],
        ),
    ]
